# Домашнє завдання 1


In [2]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
natural_numbers = np.array([i for i in range(1, 11)], dtype=int)
print(natural_numbers)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
zero_matrix = np.zeros((3,3), dtype=int)

print(zero_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
min_border = 1
max_border = 10
random_matrix = np.random.randint(min_border, max_border, (5,5))

print(random_matrix)

[[3 5 9 1 4]
 [9 4 4 1 5]
 [4 5 1 5 9]
 [8 9 4 2 8]
 [9 7 4 3 1]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
min_border = 0
max_border = 1
random_matrix = np.random.uniform(min_border, max_border, (4,4))

print(random_matrix)

[[0.39269872 0.6474154  0.60868747 0.7409322 ]
 [0.18606068 0.78036373 0.05755161 0.65698507]
 [0.24346663 0.17746067 0.03077902 0.49770389]
 [0.7729053  0.23573651 0.98501328 0.25236237]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
min_border = 1
max_border = 10
first_vector = np.random.randint(min_border, max_border, 5)
second_vector = np.random.randint(min_border, max_border, 5)

print(first_vector)
print(second_vector)
print(f"Sum of two vectors: {first_vector + second_vector}")
print(f"Difference of two vectors: {first_vector - second_vector}")
print(f"Multiplication of two vectors: {first_vector * second_vector}")

[4 4 9 1 9]
[2 8 5 4 4]
Sum of two vectors: [ 6 12 14  5 13]
Difference of two vectors: [ 2 -4  4 -3  5]
Multiplication of two vectors: [ 8 32 45  4 36]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
min_border = 1
max_border = 10

first_vector = np.random.randint(min_border, max_border, 7)
second_vector = np.random.randint(min_border, max_border, 7)
scalar_product = np.dot(first_vector, second_vector)

print(f"Scalar product: {scalar_product}")


Scalar product: 122


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
min_border = 1
max_border = 10
first_matrix = np.random.randint(min_border, max_border, (2,2))
second_matrix = np.random.randint(min_border, max_border, (2,3))
mult_matrixs = np.dot(first_matrix, second_matrix)

print("Multiplication of two matrix 2x2 and 2x3:")
print(mult_matrixs)

Multiplication of two matrix 2x2 and 2x3:
[[ 94  79 102]
 [ 81  48  69]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [17]:
min_border = 1
max_border = 10
test_matrix = np.random.randint(min_border, max_border, (3,3))
print(test_matrix)
det_test_matrix = np.linalg.det(test_matrix)

if det_test_matrix != 0:
    print("The determinant of matrix det_test_matrix is not zero. The inverse matrix exists.")
    reversed_matrix = np.linalg.inv(test_matrix )
    print(reversed_matrix)
else:
    print("The determinant of matrix det_test_matrix is zero. The inverse matrix does not exist.")


[[4 8 7]
 [6 1 8]
 [6 6 2]]
The determinant of matrix det_test_matrix is not zero. The inverse matrix exists.
[[-0.14649682  0.08280255  0.18152866]
 [ 0.11464968 -0.10828025  0.03184713]
 [ 0.0955414   0.07643312 -0.14012739]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [5]:
min_border = 0
max_border = 1
test_matrix = np.random.uniform(min_border, max_border, (4,4))
print("A four by four matrix")
print(test_matrix)

transposed_matrix = test_matrix.T
print("Transposed matrix")
print(transposed_matrix)

A four by four matrix
[[0.60923672 0.25922412 0.11100859 0.30874215]
 [0.16798571 0.64431382 0.01892604 0.54023251]
 [0.22614465 0.62357941 0.00849888 0.18724076]
 [0.20900641 0.43164377 0.30147517 0.55184227]]
Transposed matrix
[[0.60923672 0.16798571 0.22614465 0.20900641]
 [0.25922412 0.64431382 0.62357941 0.43164377]
 [0.11100859 0.01892604 0.00849888 0.30147517]
 [0.30874215 0.54023251 0.18724076 0.55184227]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [6]:
min_border = 1
max_border = 10

test_matrix = np.random.randint(min_border, max_border, (3,4))
test_vector = np.random.randint(min_border, max_border, 4)
result = np.dot(test_matrix, test_vector)

print("A three by four matrix")
print(test_matrix)
print("Vector size 4")
print(test_vector)
print("Result")
print(result)


A three by four matrix
[[2 2 3 7]
 [8 1 2 4]
 [9 3 1 7]]
Vector size 4
[4 9 4 1]
Result
[45 53 74]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [7]:
min_border = 0
max_border = 1

test_matrix = np.random.uniform(min_border, max_border, (2,3))
test_vector = np.random.uniform(min_border, max_border, 3)
result = np.dot(test_matrix, test_vector)

print("A two by three matrix")
print(test_matrix)
print("Vector size 3")
print(test_vector)
print("Result")
print(result)

A two by three matrix
[[0.71996755 0.51027769 0.67061038]
 [0.2798076  0.05298253 0.52432485]]
Vector size 3
[0.28971096 0.05481267 0.63186128]
Result
[0.6602849  0.41526801]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [8]:
min_border = 1
max_border = 10

first_matrix = np.random.randint(min_border, max_border, (2,2))
second_matrix = np.random.randint(min_border, max_border, (2,2))
multiplied_matrices = np.multiply(first_matrix, second_matrix)

print("First matrix:")
print(first_matrix)
print("Second matrix:")
print(second_matrix)
print("Multiplied matrix:")
print(multiplied_matrices)

First matrix:
[[9 1]
 [2 7]]
Second matrix:
[[9 6]
 [9 2]]
Multiplied matrix:
[[81  6]
 [18 14]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [11]:
min_border = 1
max_border = 10

first_matrix = np.random.randint(min_border, max_border, (2,2))
second_matrix = np.random.randint(min_border, max_border, (2,2))
result = np.dot(first_matrix, second_matrix)

print("First matrix:")
print(first_matrix)
print("Second matrix:")
print(second_matrix)
print("Result:")
print(result)



First matrix:
[[3 2]
 [8 7]]
Second matrix:
[[9 4]
 [6 3]]
Result:
[[ 39  18]
 [114  53]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [21]:
min_border = 1
max_border = 100

temp_matrix = np.random.randint(min_border, max_border, (5,5))
sum_result = np.sum(temp_matrix)

print("Matrix:")
print(temp_matrix)
print("Sum of matrix elements:")
print(sum_result)


Matrix:
[[69 75 18 13 80]
 [92 75 98 14 67]
 [42 56 99 29 77]
 [82 72 95 92 94]
 [ 8  1 67 13 41]]
Sum of matrix elements:
1469


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [23]:
min_border = 1
max_border = 10

first_matrix = np.random.randint(min_border, max_border, (4,4))
second_matrix = np.random.randint(min_border, max_border, (4,4))
matrix_difference = first_matrix - second_matrix

print("First matrix:")
print(first_matrix)
print("Second matrix:")
print(second_matrix)
print("Matrix difference:")
print(matrix_difference)



First matrix:
[[2 3 7 9]
 [5 5 5 5]
 [8 4 4 6]
 [1 1 6 2]]
Second matrix:
[[2 9 8 5]
 [1 8 5 7]
 [5 7 6 9]
 [8 5 5 7]]
Matrix difference:
[[ 0 -6 -1  4]
 [ 4 -3  0 -2]
 [ 3 -3 -2 -3]
 [-7 -4  1 -5]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [29]:
min_border = 0
max_border = 1
test_matrix = np.random.uniform(min_border, max_border, (3,3))
sum_row = np.sum(test_matrix, axis=1)
result = sum_row.reshape(-1, 1)

print("Matrix:")
print(test_matrix)
print("Column vector:")
print(result)


Matrix:
[[0.47470742 0.71494911 0.22902121]
 [0.67440909 0.65945491 0.47036153]
 [0.95448014 0.54705297 0.88736168]]
Column vector:
[[1.41867774]
 [1.80422553]
 [2.38889479]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [33]:
min_border = 1
max_border = 5
test_matrix = np.random.randint(min_border, max_border, (3,4))
quadro_matrix = np.square(test_matrix)

print("Matrix:")
print(test_matrix)
print("A matrix with the squares of these numbers:")
print(quadro_matrix)

Matrix:
[[3 4 4 4]
 [2 1 4 4]
 [3 2 1 1]]
A matrix with the squares of these numbers:
[[ 9 16 16 16]
 [ 4  1 16 16]
 [ 9  4  1  1]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [52]:
min_border = 1
max_border = 50

test_vector = np.random.randint(min_border, max_border, 4)
square_root = np.sqrt(test_vector)

print("Vector:")
print(test_vector)
print("square_root")
print(square_root)

Vector:
[ 7 25 25 44]
square_root
[2.64575131 5.         5.         6.63324958]
